force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Date_Listed__c.field-meta.xml
<CustomField>
    <fullName>Date_Listed__c</fullName>
    <defaultValue>TODAY() - 10</defaultValue>
    <label>Date Listed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Asking Price</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Contracted</fullName>
            </value>
            <value>
                <fullName>Pre Market</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Under Agreement</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PropertyServices.cls
public with sharing class PropertyServices {
    @AuraEnabled(casheable=true);
    public static List<Property__c> getProperties() {
        try {
            List<Property__c> propertyList = [
                SELECT Name, 
                Date_Listed__c, 
                Days_On_Market__c, 
                Price__c 
                FROM Property__c 
                WITH SECURITY_ENFORCED 
                ORDER BY Days_On_Market__c];
                return propertyList;
        } catch (Exception ex) {
           throw new AuraHandledException(ex.getMessage());
        }

    }


    public static Property__c createProperty(String propertyName){
        try {
            Property__c newProperty = new Property__c();
            newProperty.Name = propertyName;
            newProperty.Date_Listed__c = Date.today();
            insert newProperty;
            return newProperty;
        } catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }

    }

    public static List<Property__c> updateProperty(){
        try {
            List<Property__c> propertyList = getProperties();

            for(Property__c property : propertyList){
                property.Status__c = 'Available';
            } 

            update propertyList;
            return propertyList;
        } catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }

}